// Put all the constant data in associative arrays to make the code more readable

const framedata = {
    amazon: {
        A1: {
            weapontypematters: true,
            perweaponata: {
                wHTH: {
                    startframe: 1,
                    actionframes: [8],
                    framesperdirection: 13,
                    animationspeed: 256
                },
                w1HS: {
                    startframe: 2,
                    actionframes: [10],
                    framesperdirection: 16,
                    animationspeed: 256
                },
                w2HS: {
                    startframe: 2,
                    actionframes: [12],
                    framesperdirection: 20,
                    animationspeed: 256
                },
                w1HT: {
                    startframe: 2,
                    actionframes: [9],
                    framesperdirection: 15,
                    animationspeed: 256
                },
                w2HT: {
                    startframe: 2,
                    actionframes: [11],
                    framesperdirection: 18,
                    animationspeed: 256
                },
                wSTF: {
                    startframe: 2,
                    actionframes: [12],
                    framesperdirection: 20,
                    animationspeed: 256
                },
                wBOW: {
                    startframe: 0,
                    actionframes: [6],
                    framesperdirection: 14,
                    animationspeed: 256
                },
                wXBW: {
                    startframe: 0,
                    actionframes: [9],
                    framesperdirection: 20,
                    animationspeed: 256
                }
            }
        }
    },
    assassin: {
        A1: {
            weapontypematters: true,
            perweaponata: {
                wHTH: {
                    startframe: 0,
                    actionframes: [6],
                    framesperdirection: 11,
                    animationspeed: 256
                },
                w1HS: {
                    startframe: 0,
                    actionframes: [7],
                    framesperdirection: 15,
                    animationspeed: 256
                },
                w2HS: {
                    startframe: 0,
                    actionframes: [11],
                    framesperdirection: 23,
                    animationspeed: 256
                },
                w1HT: {
                    startframe: 0,
                    actionframes: [7],
                    framesperdirection: 15,
                    animationspeed: 256
                },
                w2HT: {
                    startframe: 0,
                    actionframes: [10],
                    framesperdirection: 23,
                    animationspeed: 256
                },
                wSTF: {
                    startframe: 0,
                    actionframes: [9],
                    framesperdirection: 19,
                    animationspeed: 256
                },
                wBOW: {
                    startframe: 0,
                    actionframes: [7],
                    framesperdirection: 16,
                    animationspeed: 256
                },
                wXBW: {
                    startframe: 0,
                    actionframes: [10],
                    framesperdirection: 21,
                    animationspeed: 256
                },
                wHT1: {
                    startframe: 0,
                    actionframes: [6],
                    framesperdirection: 11,
                    animationspeed: 208
                }
            }
        }
    },
    barbarian: {
        A1: {
            weapontypematters: true,
            perweaponata: {
                wHTH: {
                    startframe: 0,
                    actionframes: [6],
                    framesperdirection: 12,
                    animationspeed: 256
                },
                w1HS: {
                    startframe: 0,
                    actionframes: [7],
                    framesperdirection: 16,
                    animationspeed: 256
                },
                w2HS: {
                    startframe: 0,
                    actionframes: [8],
                    framesperdirection: 18,
                    animationspeed: 256
                },
                w1HT: {
                    startframe: 0,
                    actionframes: [7],
                    framesperdirection: 16,
                    animationspeed: 256
                },
                w2HT: {
                    startframe: 0,
                    actionframes: [9],
                    framesperdirection: 19,
                    animationspeed: 256
                },
                wSTF: {
                    startframe: 0,
                    actionframes: [9],
                    framesperdirection: 19,
                    animationspeed: 256
                },
                wBOW: {
                    startframe: 0,
                    actionframes: [7],
                    framesperdirection: 15,
                    animationspeed: 256
                },
                wXBW: {
                    startframe: 0,
                    actionframes: [10],
                    framesperdirection: 20,
                    animationspeed: 256
                },
                w1SS: {
                    startframe: 0,
                    actionframes: [7],
                    framesperdirection: 16,
                    animationspeed: 256
                }
            }
        }
    },
    druid: {
        A1: {
            weapontypematters: true,
            perweaponata: {
                wHTH: {
                    startframe: 0,
                    actionframes: [8],
                    framesperdirection: 16,
                    animationspeed: 256
                },
                w1HS: {
                    startframe: 0,
                    actionframes: [9],
                    framesperdirection: 19,
                    animationspeed: 256
                },
                w2HS: {
                    startframe: 0,
                    actionframes: [10],
                    framesperdirection: 21,
                    animationspeed: 256
                },
                w1HT: {
                    startframe: 0,
                    actionframes: [8],
                    framesperdirection: 19,
                    animationspeed: 256
                },
                w2HT: {
                    startframe: 0,
                    actionframes: [9],
                    framesperdirection: 23,
                    animationspeed: 256
                },
                wSTF: {
                    startframe: 0,
                    actionframes: [9],
                    framesperdirection: 17,
                    animationspeed: 256
                },
                wBOW: {
                    startframe: 0,
                    actionframes: [8],
                    framesperdirection: 16,
                    animationspeed: 256
                },
                wXBW: {
                    startframe: 0,
                    actionframes: [10],
                    framesperdirection: 20,
                    animationspeed: 256
                }
            }
        }
    },
    necromancer: {
        A1: {
            weapontypematters: true,
            perweaponata: {
                wHTH: {
                    startframe: 0,
                    actionframes: [8],
                    framesperdirection: 15,
                    animationspeed: 256
                },
                w1HS: {
                    startframe: 0,
                    actionframes: [9],
                    framesperdirection: 19,
                    animationspeed: 256
                },
                w2HS: {
                    startframe: 0,
                    actionframes: [11],
                    framesperdirection: 23,
                    animationspeed: 256
                },
                w1HT: {
                    startframe: 0,
                    actionframes: [9],
                    framesperdirection: 19,
                    animationspeed: 256
                },
                w2HT: {
                    startframe: 0,
                    actionframes: [10],
                    framesperdirection: 24,
                    animationspeed: 256
                },
                wSTF: {
                    startframe: 0,
                    actionframes: [11],
                    framesperdirection: 20,
                    animationspeed: 256
                },
                wBOW: {
                    startframe: 0,
                    actionframes: [9],
                    framesperdirection: 18,
                    animationspeed: 256
                },
                wXBW: {
                    startframe: 0,
                    actionframes: [11],
                    framesperdirection: 20,
                    animationspeed: 256
                }
            }
        }
    },
    paladin: {
        A1: {
            weapontypematters: true,
            perweaponata: {
                wHTH: {
                    startframe: 0,
                    actionframes: [7],
                    framesperdirection: 14,
                    animationspeed: 256
                },
                w1HS: {
                    startframe: 0,
                    actionframes: [7],
                    framesperdirection: 15,
                    animationspeed: 256
                },
                w2HS: {
                    startframe: 0,
                    actionframes: [8],
                    framesperdirection: 18,
                    animationspeed: 256
                },
                w1HT: {
                    startframe: 0,
                    actionframes: [8],
                    framesperdirection: 17,
                    animationspeed: 256
                },
                w2HT: {
                    startframe: 0,
                    actionframes: [8],
                    framesperdirection: 20,
                    animationspeed: 256
                },
                wSTF: {
                    startframe: 0,
                    actionframes: [9],
                    framesperdirection: 18,
                    animationspeed: 256
                },
                wBOW: {
                    startframe: 0,
                    actionframes: [8],
                    framesperdirection: 16,
                    animationspeed: 256
                },
                wXBW: {
                    startframe: 0,
                    actionframes: [10],
                    framesperdirection: 20,
                    animationspeed: 256
                }
            }
        }
    },
    sorceress: {
        A1: {
            weapontypematters: true,
            perweaponata: {
                wHTH: {
                    startframe: 1,
                    actionframes: [9],
                    framesperdirection: 16,
                    animationspeed: 256
                },
                w1HS: {
                    startframe: 2,
                    actionframes: [12],
                    framesperdirection: 20,
                    animationspeed: 256
                },
                w2HS: {
                    startframe: 2,
                    actionframes: [14],
                    framesperdirection: 24,
                    animationspeed: 256
                },
                w1HT: {
                    startframe: 2,
                    actionframes: [11],
                    framesperdirection: 19,
                    animationspeed: 256
                },
                w2HT: {
                    startframe: 2,
                    actionframes: [13],
                    framesperdirection: 23,
                    animationspeed: 256
                },
                wSTF: {
                    startframe: 2,
                    actionframes: [11],
                    framesperdirection: 18,
                    animationspeed: 256
                },
                wBOW: {
                    startframe: 0,
                    actionframes: [9],
                    framesperdirection: 17,
                    animationspeed: 256
                },
                wXBW: {
                    startframe: 0,
                    actionframes: [11],
                    framesperdirection: 20,
                    animationspeed: 256
                }
            }
        }
    },
    werewolf: {
        A1: {
            weapontypematters: false,
            perweaponata: {
                wHTH: {
                    startframe: 0,
                    actionframes: [7],
                    framesperdirection: 13,
                    animationspeed: 256
                }
            }
        },
        S3: {
            weapontypematters: false,
            perweaponata: {
                wHTH: {
                    startframe: 0,
                    actionframes: [6],
                    framesperdirection: 10,
                    animationspeed: 240
                }
            }
        }
    },
    werebear: {
        A1: {
            weapontypematters: false,
            perweaponata: {
                wHTH: {
                    startframe: 0,
                    actionframes: [7],
                    framesperdirection: 12,
                    animationspeed: 224
                }
            }
        },
        S3: {
            weapontypematters: false,
            perweaponata: {
                wHTH: {
                    startframe: 0,
                    actionframes: [6],
                    framesperdirection: 10,
                    animationspeed: 208
                }
            }
        }
    }
};


const skilldata ={
    normalattack: {
        animation: "A1",
        isrollbackskill: false,
        hitcount: 1,
        issequence: false,
        skillfactor: 0
    },
    feralrage: {
        animation: "A1",
        isrollbackskill: false,
        hitcount: 1,
        issequence: false,
        skillfactor: 0
    },
    bite: {
        animation: "S3",
        isrollbackskill: false,
        hitcount: 1,
        issequence: false,
        skillfactor: 0
    },
    fury: {
        animation: "A1",
        isrollbackskill: true,
        rollbackamount: 70, // extracted skills.txt from PTR2 game data shows this is 70; patch notes are wrong.
        hitcount: 5,
        issequence: false,
        skillfactor: 0
    }
    // TODO: Do all the skills in D2
};


const animationames = {
    wHTH: "Unarmed",
    w1HS: "1-Handed Swinging Weapon",
    w2HS: "2-Handed Swinging Weapon (sword)",
    wSTF: "2-Handed Swinging Weapon (staff/axe/polearm/hammer)",
    w1HT: "1-Handed Thrusting Weapon",
    w2HT: "2-Handed Thrusting Weapon",
    wBOW: "Bow",
    wXBW: "Crossbow",
    wHT1: "Claws"
    // TODO: dual wielding
};

// TODO: Fill in isonehandsword and isjavelinorpolearm so weapon options for merc can be done
// (presently they are all set to false)

const weaponlist = {
    unarmed: {
        printname: "[unarmed]",
        wsm: 0,
        wclass: "wHTH",
        zononly: false,
        isorb: false,
        isonehandsword: false,
        isjavelinorpolearm: false,
    },
    AncientAxe: {
        printname: "Ancient Axe",
        wsm: 10,
        wclass: "wSTF",
        zononly: false,
        isorb: false,
        isonehandsword: false,
        isjavelinorpolearm: false,
    },
    AncientSword: {
        printname: "Ancient Sword",
        wsm: 0,
        wclass: "w1HS",
        zononly: false,
        isorb: false,
        isonehandsword: false,
        isjavelinorpolearm: false,
    },
    Arbalest: {
        printname: "Arbalest",
        wsm: -10,
        wclass: "wXBW",
        zononly: false,
        isorb: false,
        isonehandsword: false,
        isjavelinorpolearm: false,
    },
    ArchonStaff: {
        printname: "Archon Staff",
        wsm: 10,
        wclass: "wSTF",
        zononly: false,
        isorb: false,
        isonehandsword: false,
        isjavelinorpolearm: false,
    },
    AshwoodBow: {
        printname: "Ashwood Bow",
        wsm: 0,
        wclass: "wBOW",
        zononly: true,
        isorb: false,
        isonehandsword: false,
        isjavelinorpolearm: false,
    },
    Ataghan: {
        printname: "Ataghan",
        wsm: -20,
        wclass: "w1HS",
        zononly: false,
        isorb: false,
        isonehandsword: false,
        isjavelinorpolearm: false,
    },
    Axe: {
        printname: "Axe",
        wsm: 10,
        wclass: "w1HS",
        zononly: false,
        isorb: false,
        isonehandsword: false,
        isjavelinorpolearm: false,
    },
    BalancedAxe: {
        printname: "Balanced Axe",
        wsm: -10,
        wclass: "w1HS",
        zononly: false,
        isorb: false,
        isonehandsword: false,
        isjavelinorpolearm: false,
    },
    BalancedKnife: {
        printname: "Balanced Knife",
        wsm: -20,
        wclass: "w1HT",
        zononly: false,
        isorb: false,
        isonehandsword: false,
        isjavelinorpolearm: false,
    },
    Ballista: {
        printname: "Ballista",
        wsm: 10,
        wclass: "wXBW",
        zononly: false,
        isorb: false,
        isonehandsword: false,
        isjavelinorpolearm: false,
    },
    BalrogBlade: {
        printname: "Balrog Blade",
        wsm: 0,
        wclass: "w2HS",
        zononly: false,
        isorb: false,
        isonehandsword: false,
        isjavelinorpolearm: false,
    },
    BalrogSpear: {
        printname: "Balrog Spear",
        wsm: 10,
        wclass: "w1HT",
        zononly: false,
        isorb: false,
        isonehandsword: false,
        isjavelinorpolearm: false,
    },
    BarbedClub: {
        printname: "Barbed Club",
        wsm: 0,
        wclass: "w1HS",
        zononly: false,
        isorb: false,
        isonehandsword: false,
        isjavelinorpolearm: false,
    },
    Bardiche: {
        printname: "Bardiche",
        wsm: 10,
        wclass: "wSTF",
        zononly: false,
        isorb: false,
        isonehandsword: false,
        isjavelinorpolearm: false,
    },
    BastardSword: {
        printname: "Bastard Sword",
        wsm: 10,
        wclass: "w2HS",
        zononly: false,
        isorb: false,
        isonehandsword: false,
        isjavelinorpolearm: false,
    },
    BattleAxe: {
        printname: "Battle Axe",
        wsm: 10,
        wclass: "wSTF",
        zononly: false,
        isorb: false,
        isonehandsword: false,
        isjavelinorpolearm: false,
    },
    BattleCestus: {
        printname: "Battle Cestus",
        wsm: -10,
        wclass: "wHT1",
        zononly: false,
        isorb: false,
        isonehandsword: false,
        isjavelinorpolearm: false,
    },
    BattleDart: {
        printname: "Battle Dart",
        wsm: 0,
        wclass: "w1HT",
        zononly: false,
        isorb: false,
        isonehandsword: false,
        isjavelinorpolearm: false,
    },
    BattleHammer: {
        printname: "Battle Hammer",
        wsm: 20,
        wclass: "w1HS",
        zononly: false,
        isorb: false,
        isonehandsword: false,
        isjavelinorpolearm: false,
    },
    BattleScythe: {
        printname: "Battle Scythe",
        wsm: -10,
        wclass: "wSTF",
        zononly: false,
        isorb: false,
        isonehandsword: false,
        isjavelinorpolearm: false,
    },
    BattleStaff: {
        printname: "Battle Staff",
        wsm: 0,
        wclass: "wSTF",
        zononly: false,
        isorb: false,
        isonehandsword: false,
        isjavelinorpolearm: false,
    },
    BattleSword: {
        printname: "Battle Sword",
        wsm: 0,
        wclass: "w1HS",
        zononly: false,
        isorb: false,
        isonehandsword: false,
        isjavelinorpolearm: false,
    },
    BeardedAxe: {
        printname: "Bearded Axe",
        wsm: 0,
        wclass: "wSTF",
        zononly: false,
        isorb: false,
        isonehandsword: false,
        isjavelinorpolearm: false,
    },
    BecdeCorbin: {
        printname: "Bec-de-Corbin",
        wsm: 0,
        wclass: "wSTF",
        zononly: false,
        isorb: false,
        isonehandsword: false,
        isjavelinorpolearm: false,
    },
    BerserkerAxe: {
        printname: "Berserker Axe",
        wsm: 0,
        wclass: "w1HS",
        zononly: false,
        isorb: false,
        isonehandsword: false,
        isjavelinorpolearm: false,
    },
    Bill: {
        printname: "Bill",
        wsm: 0,
        wclass: "wSTF",
        zononly: false,
        isorb: false,
        isonehandsword: false,
        isjavelinorpolearm: false,
    },
    BladeBow: {
        printname: "Blade Bow",
        wsm: -10,
        wclass: "wBOW",
        zononly: false,
        isorb: false,
        isonehandsword: false,
        isjavelinorpolearm: false,
    },
    BladeTalons: {
        printname: "Blade Talons",
        wsm: -20,
        wclass: "wHT1",
        zononly: false,
        isorb: false,
        isonehandsword: false,
        isjavelinorpolearm: false,
    },
    Blade: {
        printname: "Blade",
        wsm: -10,
        wclass: "w1HT",
        zononly: false,
        isorb: false,
        isonehandsword: false,
        isjavelinorpolearm: false,
    },
    BoneKnife: {
        printname: "Bone Knife",
        wsm: -20,
        wclass: "w1HT",
        zononly: false,
        isorb: false,
        isonehandsword: false,
        isjavelinorpolearm: false,
    },
    BoneWand: {
        printname: "Bone Wand",
        wsm: -20,
        wclass: "w1HS",
        zononly: false,
        isorb: false,
        isonehandsword: false,
        isjavelinorpolearm: false,
    },
    Brandistock: {
        printname: "Brandistock",
        wsm: -20,
        wclass: "w2HT",
        zononly: false,
        isorb: false,
        isonehandsword: false,
        isjavelinorpolearm: false,
    },
    BroadAxe: {
        printname: "Broad Axe",
        wsm: 0,
        wclass: "wSTF",
        zononly: false,
        isorb: false,
        isonehandsword: false,
        isjavelinorpolearm: false,
    },
    BroadSword: {
        printname: "Broad Sword",
        wsm: 0,
        wclass: "w1HS",
        zononly: false,
        isorb: false,
        isonehandsword: false,
        isjavelinorpolearm: false,
    },
    BurntWand: {
        printname: "Burnt Wand",
        wsm: 0,
        wclass: "w1HS",
        zononly: false,
        isorb: false,
        isonehandsword: false,
        isjavelinorpolearm: false,
    },
    Caduceus: {
        printname: "Caduceus",
        wsm: -10,
        wclass: "w1HS",
        zononly: false,
        isorb: false,
        isonehandsword: false,
        isjavelinorpolearm: false,
    },
    CedarBow: {
        printname: "Cedar Bow",
        wsm: 0,
        wclass: "wBOW",
        zononly: false,
        isorb: false,
        isonehandsword: false,
        isjavelinorpolearm: false,
    },
    CedarStaff: {
        printname: "Cedar Staff",
        wsm: 10,
        wclass: "wSTF",
        zononly: false,
        isorb: false,
        isonehandsword: false,
        isjavelinorpolearm: false,
    },
    CeremonialBow: {
        printname: "Ceremonial Bow",
        wsm: 10,
        wclass: "wBOW",
        zononly: true,
        isorb: false,
        isonehandsword: false,
        isjavelinorpolearm: false,
    },
    CeremonialJavelin: {
        printname: "Ceremonial Javelin",
        wsm: -10,
        wclass: "w1HT",
        zononly: true,
        isorb: false,
        isonehandsword: false,
        isjavelinorpolearm: false,
    },
    CeremonialPike: {
        printname: "Ceremonial Pike",
        wsm: 20,
        wclass: "w2HT",
        zononly: true,
        isorb: false,
        isonehandsword: false,
        isjavelinorpolearm: false,
    },
    CeremonialSpear: {
        printname: "Ceremonial Spear",
        wsm: 0,
        wclass: "w2HT",
        zononly: true,
        isorb: false,
        isonehandsword: false,
        isjavelinorpolearm: false,
    },
    Cestus: {
        printname: "Cestus",
        wsm: 0,
        wclass: "wHT1",
        zononly: false,
        isorb: false,
        isonehandsword: false,
        isjavelinorpolearm: false,
    },
    ChampionAxe: {
        printname: "Champion Axe",
        wsm: -10,
        wclass: "wSTF",
        zononly: false,
        isorb: false,
        isonehandsword: false,
        isjavelinorpolearm: false,
    },
    ChampionSword: {
        printname: "Champion Sword",
        wsm: -10,
        wclass: "w2HS",
        zononly: false,
        isorb: false,
        isonehandsword: false,
        isjavelinorpolearm: false,
    },
    ChuKoNu: {
        printname: "Chu-Ko-Nu",
        wsm: -60,
        wclass: "wXBW",
        zononly: false,
        isorb: false,
        isonehandsword: false,
        isjavelinorpolearm: false,
    },
    Cinquedeas: {
        printname: "Cinquedeas",
        wsm: -20,
        wclass: "w1HT",
        zononly: false,
        isorb: false,
        isonehandsword: false,
        isjavelinorpolearm: false,
    },
    ClaspedOrb: {
        printname: "Clasped Orb",
        wsm: 0,
        wclass: "w1HS",
        zononly: false,
        isorb: true,
        isonehandsword: false,
        isjavelinorpolearm: false,
    },
    Claws: {
        printname: "Claws",
        wsm: -10,
        wclass: "wHT1",
        zononly: false,
        isorb: false,
        isonehandsword: false,
        isjavelinorpolearm: false,
    },
    Claymore: {
        printname: "Claymore",
        wsm: 10,
        wclass: "w2HS",
        zononly: false,
        isorb: false,
        isonehandsword: false,
        isjavelinorpolearm: false,
    },
    Cleaver: {
        printname: "Cleaver",
        wsm: 10,
        wclass: "w1HS",
        zononly: false,
        isorb: false,
        isonehandsword: false,
        isjavelinorpolearm: false,
    },
    CloudySphere: {
        printname: "Cloudy Sphere",
        wsm: 0,
        wclass: "w1HS",
        zononly: false,
        isorb: true,
        isonehandsword: false,
        isjavelinorpolearm: false,
    },
    Club: {
        printname: "Club",
        wsm: -10,
        wclass: "w1HS",
        zononly: false,
        isorb: false,
        isonehandsword: false,
        isjavelinorpolearm: false,
    },
    ColossusBlade: {
        printname: "Colossus Blade",
        wsm: 5,
        wclass: "w2HS",
        zononly: false,
        isorb: false,
        isonehandsword: false,
        isjavelinorpolearm: false,
    },
    ColossusCrossbow: {
        printname: "Colossus Crossbow",
        wsm: 10,
        wclass: "wXBW",
        zononly: false,
        isorb: false,
        isonehandsword: false,
        isjavelinorpolearm: false,
    },
    ColossusSword: {
        printname: "Colossus Sword",
        wsm: 10,
        wclass: "w2HS",
        zononly: false,
        isorb: false,
        isonehandsword: false,
        isjavelinorpolearm: false,
    },
    ColossusVoulge: {
        printname: "Colossus Voulge",
        wsm: 10,
        wclass: "wSTF",
        zononly: false,
        isorb: false,
        isonehandsword: false,
        isjavelinorpolearm: false,
    },
    CompositeBow: {
        printname: "Composite Bow",
        wsm: -10,
        wclass: "wBOW",
        zononly: false,
        isorb: false,
        isonehandsword: false,
        isjavelinorpolearm: false,
    },
    ConquestSword: {
        printname: "Conquest Sword",
        wsm: 0,
        wclass: "w1HS",
        zononly: false,
        isorb: false,
        isonehandsword: false,
        isjavelinorpolearm: false,
    },
    Crossbow: {
        printname: "Crossbow",
        wsm: 0,
        wclass: "wXBW",
        zononly: false,
        isorb: false,
        isonehandsword: false,
        isjavelinorpolearm: false,
    },
    Crowbill: {
        printname: "Crowbill",
        wsm: -10,
        wclass: "w1HS",
        zononly: false,
        isorb: false,
        isonehandsword: false,
        isjavelinorpolearm: false,
    },
    CrusaderBow: {
        printname: "Crusader Bow",
        wsm: 10,
        wclass: "wBOW",
        zononly: false,
        isorb: false,
        isonehandsword: false,
        isjavelinorpolearm: false,
    },
    CrypticAxe: {
        printname: "Cryptic Axe",
        wsm: 10,
        wclass: "wSTF",
        zononly: false,
        isorb: false,
        isonehandsword: false,
        isjavelinorpolearm: false,
    },
    CrypticSword: {
        printname: "Cryptic Sword",
        wsm: -10,
        wclass: "w1HS",
        zononly: false,
        isorb: false,
        isonehandsword: false,
        isjavelinorpolearm: false,
    },
    CrystalSword: {
        printname: "Crystal Sword",
        wsm: 0,
        wclass: "w1HS",
        zononly: false,
        isorb: false,
        isonehandsword: false,
        isjavelinorpolearm: false,
    },
    CrystallineGlobe: {
        printname: "Crystalline Globe",
        wsm: -10,
        wclass: "w1HS",
        zononly: false,
        isorb: true,
        isonehandsword: false,
        isjavelinorpolearm: false,
    },
    Cudgel: {
        printname: "Cudgel",
        wsm: -10,
        wclass: "w1HS",
        zononly: false,
        isorb: false,
        isonehandsword: false,
        isjavelinorpolearm: false,
    },
    Cutlass: {
        printname: "Cutlass",
        wsm: -30,
        wclass: "w1HS",
        zononly: false,
        isorb: false,
        isonehandsword: false,
        isjavelinorpolearm: false,
    },
    DacianFalx: {
        printname: "Dacian Falx",
        wsm: 10,
        wclass: "w2HS",
        zononly: false,
        isorb: false,
        isonehandsword: false,
        isjavelinorpolearm: false,
    },
    Dagger: {
        printname: "Dagger",
        wsm: -20,
        wclass: "w1HT",
        zononly: false,
        isorb: false,
        isonehandsword: false,
        isjavelinorpolearm: false,
    },
    Decapitator: {
        printname: "Decapitator",
        wsm: 10,
        wclass: "wSTF",
        zononly: false,
        isorb: false,
        isonehandsword: false,
        isjavelinorpolearm: false,
    },
    DemonCrossbow: {
        printname: "Demon Crossbow",
        wsm: -60,
        wclass: "wXBW",
        zononly: false,
        isorb: false,
        isonehandsword: false,
        isjavelinorpolearm: false,
    },
    DemonHeart: {
        printname: "Demon Heart",
        wsm: 0,
        wclass: "w1HS",
        zononly: false,
        isorb: true,
        isonehandsword: false,
        isjavelinorpolearm: false,
    },
    DevilStar: {
        printname: "Devil Star",
        wsm: 10,
        wclass: "w1HS",
        zononly: false,
        isorb: false,
        isonehandsword: false,
        isjavelinorpolearm: false,
    },
    DiamondBow: {
        printname: "Diamond Bow",
        wsm: 0,
        wclass: "wBOW",
        zononly: false,
        isorb: false,
        isonehandsword: false,
        isjavelinorpolearm: false,
    },
    DimensionalBlade: {
        printname: "Dimensional Blade",
        wsm: 0,
        wclass: "w1HS",
        zononly: false,
        isorb: false,
        isonehandsword: false,
        isjavelinorpolearm: false,
    },
    DimensionalShard: {
        printname: "Dimensional Shard",
        wsm: 10,
        wclass: "w1HS",
        zononly: false,
        isorb: true,
        isonehandsword: false,
        isjavelinorpolearm: false,
    },
    Dirk: {
        printname: "Dirk",
        wsm: 0,
        wclass: "w1HT",
        zononly: false,
        isorb: false,
        isonehandsword: false,
        isjavelinorpolearm: false,
    },
    DivineScepter: {
        printname: "Divine Scepter",
        wsm: -10,
        wclass: "w1HS",
        zononly: false,
        isorb: false,
        isonehandsword: false,
        isjavelinorpolearm: false,
    },
    DoubleAxe: {
        printname: "Double Axe",
        wsm: 10,
        wclass: "w1HS",
        zononly: false,
        isorb: false,
        isonehandsword: false,
        isjavelinorpolearm: false,
    },
    DoubleBow: {
        printname: "Double Bow",
        wsm: -10,
        wclass: "wBOW",
        zononly: false,
        isorb: false,
        isonehandsword: false,
        isjavelinorpolearm: false,
    },
    EagleOrb: {
        printname: "Eagle Orb",
        wsm: -10,
        wclass: "w1HS",
        zononly: false,
        isorb: true,
        isonehandsword: false,
        isjavelinorpolearm: false,
    },
    EdgeBow: {
        printname: "Edge Bow",
        wsm: 5,
        wclass: "wBOW",
        zononly: false,
        isorb: false,
        isonehandsword: false,
        isjavelinorpolearm: false,
    },
    ElderStaff: {
        printname: "Elder Staff",
        wsm: 0,
        wclass: "wSTF",
        zononly: false,
        isorb: false,
        isonehandsword: false,
        isjavelinorpolearm: false,
    },
    EldritchOrb: {
        printname: "Eldritch Orb",
        wsm: -10,
        wclass: "w1HS",
        zononly: false,
        isorb: true,
        isonehandsword: false,
        isjavelinorpolearm: false,
    },
    ElegantBlade: {
        printname: "Elegant Blade",
        wsm: -10,
        wclass: "w1HS",
        zononly: false,
        isorb: false,
        isonehandsword: false,
        isjavelinorpolearm: false,
    },
    Espandon: {
        printname: "Espandon",
        wsm: 0,
        wclass: "w2HS",
        zononly: false,
        isorb: false,
        isonehandsword: false,
        isjavelinorpolearm: false,
    },
    EttinAxe: {
        printname: "Ettin Axe",
        wsm: 10,
        wclass: "w1HS",
        zononly: false,
        isorb: false,
        isonehandsword: false,
        isjavelinorpolearm: false,
    },
    ExecutionerSword: {
        printname: "Executioner Sword",
        wsm: 10,
        wclass: "w2HS",
        zononly: false,
        isorb: false,
        isonehandsword: false,
        isjavelinorpolearm: false,
    },
    Falcata: {
        printname: "Falcata",
        wsm: 0,
        wclass: "w1HS",
        zononly: false,
        isorb: false,
        isonehandsword: false,
        isjavelinorpolearm: false,
    },
    Falchion: {
        printname: "Falchion",
        wsm: 20,
        wclass: "w1HS",
        zononly: false,
        isorb: false,
        isonehandsword: false,
        isjavelinorpolearm: false,
    },
    FangedKnife: {
        printname: "Fanged Knife",
        wsm: -20,
        wclass: "w1HT",
        zononly: false,
        isorb: false,
        isonehandsword: false,
        isjavelinorpolearm: false,
    },
    Fascia: {
        printname: "Fascia",
        wsm: 10,
        wclass: "wHT1",
        zononly: false,
        isorb: false,
        isonehandsword: false,
        isjavelinorpolearm: false,
    },
    FeralAxe: {
        printname: "Feral Axe",
        wsm: -15,
        wclass: "wSTF",
        zononly: false,
        isorb: false,
        isonehandsword: false,
        isjavelinorpolearm: false,
    },
    FeralClaws: {
        printname: "Feral Claws",
        wsm: -20,
        wclass: "wHT1",
        zononly: false,
        isorb: false,
        isonehandsword: false,
        isjavelinorpolearm: false,
    },
    Flail: {
        printname: "Flail",
        wsm: -10,
        wclass: "w1HS",
        zononly: false,
        isorb: false,
        isonehandsword: false,
        isjavelinorpolearm: false,
    },
    Flamberge: {
        printname: "Flamberge",
        wsm: -10,
        wclass: "w2HS",
        zononly: false,
        isorb: false,
        isonehandsword: false,
        isjavelinorpolearm: false,
    },
    FlangedMace: {
        printname: "Flanged Mace",
        wsm: 0,
        wclass: "w1HS",
        zononly: false,
        isorb: false,
        isonehandsword: false,
        isjavelinorpolearm: false,
    },
    FlyingAxe: {
        printname: "Flying Axe",
        wsm: 10,
        wclass: "w1HS",
        zononly: false,
        isorb: false,
        isonehandsword: false,
        isjavelinorpolearm: false,
    },
    Francisca: {
        printname: "Francisca",
        wsm: 10,
        wclass: "w1HS",
        zononly: false,
        isorb: false,
        isonehandsword: false,
        isjavelinorpolearm: false,
    },
    Fuscina: {
        printname: "Fuscina",
        wsm: 0,
        wclass: "w2HT",
        zononly: false,
        isorb: false,
        isonehandsword: false,
        isjavelinorpolearm: false,
    },
    GhostGlaive: {
        printname: "Ghost Glaive",
        wsm: 20,
        wclass: "w1HT",
        zononly: false,
        isorb: false,
        isonehandsword: false,
        isjavelinorpolearm: false,
    },
    GhostSpear: {
        printname: "Ghost Spear",
        wsm: 0,
        wclass: "w2HT",
        zononly: false,
        isorb: false,
        isonehandsword: false,
        isjavelinorpolearm: false,
    },
    GhostWand: {
        printname: "Ghost Wand",
        wsm: 10,
        wclass: "w1HS",
        zononly: false,
        isorb: false,
        isonehandsword: false,
        isjavelinorpolearm: false,
    },
    GiantAxe: {
        printname: "Giant Axe",
        wsm: 10,
        wclass: "wSTF",
        zononly: false,
        isorb: false,
        isonehandsword: false,
        isjavelinorpolearm: false,
    },
    GiantSword: {
        printname: "Giant Sword",
        wsm: 0,
        wclass: "w2HS",
        zononly: false,
        isorb: false,
        isonehandsword: false,
        isjavelinorpolearm: false,
    },
    GiantThresher: {
        printname: "Giant Thresher",
        wsm: -10,
        wclass: "wSTF",
        zononly: false,
        isorb: false,
        isonehandsword: false,
        isjavelinorpolearm: false,
    },
    Gladius: {
        printname: "Gladius",
        wsm: 0,
        wclass: "w1HS",
        zononly: false,
        isorb: false,
        isonehandsword: false,
        isjavelinorpolearm: false,
    },
    Glaive: {
        printname: "Glaive",
        wsm: 20,
        wclass: "w1HT",
        zononly: false,
        isorb: false,
        isonehandsword: false,
        isjavelinorpolearm: false,
    },
    GloriousAxe: {
        printname: "Glorious Axe",
        wsm: 10,
        wclass: "wSTF",
        zononly: false,
        isorb: false,
        isonehandsword: false,
        isjavelinorpolearm: false,
    },
    GlowingOrb: {
        printname: "Glowing Orb",
        wsm: -10,
        wclass: "w1HS",
        zononly: false,
        isorb: true,
        isonehandsword: false,
        isjavelinorpolearm: false,
    },
    GnarledStaff: {
        printname: "Gnarled Staff",
        wsm: 10,
        wclass: "wSTF",
        zononly: false,
        isorb: false,
        isonehandsword: false,
        isjavelinorpolearm: false,
    },
    GorgonCrossbow: {
        printname: "Gorgon Crossbow",
        wsm: 0,
        wclass: "wXBW",
        zononly: false,
        isorb: false,
        isonehandsword: false,
        isjavelinorpolearm: false,
    },
    GothicAxe: {
        printname: "Gothic Axe",
        wsm: -10,
        wclass: "wSTF",
        zononly: false,
        isorb: false,
        isonehandsword: false,
        isjavelinorpolearm: false,
    },
    GothicBow: {
        printname: "Gothic Bow",
        wsm: 10,
        wclass: "wBOW",
        zononly: false,
        isorb: false,
        isonehandsword: false,
        isjavelinorpolearm: false,
    },
    GothicStaff: {
        printname: "Gothic Staff",
        wsm: 0,
        wclass: "wSTF",
        zononly: false,
        isorb: false,
        isonehandsword: false,
        isjavelinorpolearm: false,
    },
    GothicSword: {
        printname: "Gothic Sword",
        wsm: 10,
        wclass: "w2HS",
        zononly: false,
        isorb: false,
        isonehandsword: false,
        isjavelinorpolearm: false,
    },
    GrandMatronBow: {
        printname: "Grand Matron Bow",
        wsm: 10,
        wclass: "wBOW",
        zononly: true,
        isorb: false,
        isonehandsword: false,
        isjavelinorpolearm: false,
    },
    GrandScepter: {
        printname: "Grand Scepter",
        wsm: 10,
        wclass: "w1HS",
        zononly: false,
        isorb: false,
        isonehandsword: false,
        isjavelinorpolearm: false,
    },
    GraveWand: {
        printname: "Grave Wand",
        wsm: 0,
        wclass: "w1HS",
        zononly: false,
        isorb: false,
        isonehandsword: false,
        isjavelinorpolearm: false,
    },
    GreatAxe: {
        printname: "Great Axe",
        wsm: -10,
        wclass: "wSTF",
        zononly: false,
        isorb: false,
        isonehandsword: false,
        isjavelinorpolearm: false,
    },
    GreatBow: {
        printname: "Great Bow",
        wsm: -10,
        wclass: "wBOW",
        zononly: false,
        isorb: false,
        isonehandsword: false,
        isjavelinorpolearm: false,
    },
    GreatMaul: {
        printname: "Great Maul",
        wsm: 20,
        wclass: "wSTF",
        zononly: false,
        isorb: false,
        isonehandsword: false,
        isjavelinorpolearm: false,
    },
    GreatPilum: {
        printname: "Great Pilum",
        wsm: 0,
        wclass: "w1HT",
        zononly: false,
        isorb: false,
        isonehandsword: false,
        isjavelinorpolearm: false,
    },
    GreatPoleaxe: {
        printname: "Great Poleaxe",
        wsm: 0,
        wclass: "wSTF",
        zononly: false,
        isorb: false,
        isonehandsword: false,
        isjavelinorpolearm: false,
    },
    GreatSword: {
        printname: "Great Sword",
        wsm: 10,
        wclass: "w2HS",
        zononly: false,
        isorb: false,
        isonehandsword: false,
        isjavelinorpolearm: false,
    },
    GreaterClaws: {
        printname: "Greater Claws",
        wsm: -20,
        wclass: "wHT1",
        zononly: false,
        isorb: false,
        isonehandsword: false,
        isjavelinorpolearm: false,
    },
    GreaterTalons: {
        printname: "Greater Talons",
        wsm: -30,
        wclass: "wHT1",
        zononly: false,
        isorb: false,
        isonehandsword: false,
        isjavelinorpolearm: false,
    },
    GrimScythe: {
        printname: "Grim Scythe",
        wsm: -10,
        wclass: "wSTF",
        zononly: false,
        isorb: false,
        isonehandsword: false,
        isjavelinorpolearm: false,
    },
    GrimWand: {
        printname: "Grim Wand",
        wsm: 0,
        wclass: "w1HS",
        zononly: false,
        isorb: false,
        isonehandsword: false,
        isjavelinorpolearm: false,
    },
    Halberd: {
        printname: "Halberd",
        wsm: 0,
        wclass: "wSTF",
        zononly: false,
        isorb: false,
        isonehandsword: false,
        isjavelinorpolearm: false,
    },
    HandAxe: {
        printname: "Hand Axe",
        wsm: 0,
        wclass: "w1HS",
        zononly: false,
        isorb: false,
        isonehandsword: false,
        isjavelinorpolearm: false,
    },
    HandScythe: {
        printname: "Hand Scythe",
        wsm: -10,
        wclass: "wHT1",
        zononly: false,
        isorb: false,
        isonehandsword: false,
        isjavelinorpolearm: false,
    },
    Harpoon: {
        printname: "Harpoon",
        wsm: -10,
        wclass: "w1HT",
        zononly: false,
        isorb: false,
        isonehandsword: false,
        isjavelinorpolearm: false,
    },
    HatchetHands: {
        printname: "Hatchet Hands",
        wsm: 10,
        wclass: "wHT1",
        zononly: false,
        isorb: false,
        isonehandsword: false,
        isjavelinorpolearm: false,
    },
    Hatchet: {
        printname: "Hatchet",
        wsm: 0,
        wclass: "w1HS",
        zononly: false,
        isorb: false,
        isonehandsword: false,
        isjavelinorpolearm: false,
    },
    HeavenlyStone: {
        printname: "Heavenly Stone",
        wsm: -10,
        wclass: "w1HS",
        zononly: false,
        isorb: true,
        isonehandsword: false,
        isjavelinorpolearm: false,
    },
    HeavyCrossbow: {
        printname: "Heavy Crossbow",
        wsm: 10,
        wclass: "wXBW",
        zononly: false,
        isorb: false,
        isonehandsword: false,
        isjavelinorpolearm: false,
    },
    HighlandBlade: {
        printname: "Highland Blade",
        wsm: -5,
        wclass: "w2HS",
        zononly: false,
        isorb: false,
        isonehandsword: false,
        isjavelinorpolearm: false,
    },
    HolyWaterSprinkler: {
        printname: "Holy Water Sprinkler",
        wsm: 10,
        wclass: "w1HS",
        zononly: false,
        isorb: false,
        isonehandsword: false,
        isjavelinorpolearm: false,
    },
    HuntersBow: {
        printname: "Hunter's Bow",
        wsm: -10,
        wclass: "wBOW",
        zononly: false,
        isorb: false,
        isonehandsword: false,
        isjavelinorpolearm: false,
    },
    Hurlbat: {
        printname: "Hurlbat",
        wsm: -10,
        wclass: "w1HS",
        zononly: false,
        isorb: false,
        isonehandsword: false,
        isjavelinorpolearm: false,
    },
    HydraBow: {
        printname: "Hydra Bow",
        wsm: 10,
        wclass: "wBOW",
        zononly: false,
        isorb: false,
        isonehandsword: false,
        isjavelinorpolearm: false,
    },
    HydraEdge: {
        printname: "Hydra Edge",
        wsm: 10,
        wclass: "w1HS",
        zononly: false,
        isorb: false,
        isonehandsword: false,
        isjavelinorpolearm: false,
    },
    HyperionJavelin: {
        printname: "Hyperion Javelin",
        wsm: -10,
        wclass: "w1HT",
        zononly: false,
        isorb: false,
        isonehandsword: false,
        isjavelinorpolearm: false,
    },
    HyperionSpear: {
        printname: "Hyperion Spear",
        wsm: -10,
        wclass: "w2HT",
        zononly: false,
        isorb: false,
        isonehandsword: false,
        isjavelinorpolearm: false,
    },
    JaggedStar: {
        printname: "Jagged Star",
        wsm: 10,
        wclass: "w1HS",
        zononly: false,
        isorb: false,
        isonehandsword: false,
        isjavelinorpolearm: false,
    },
    JaredsStone: {
        printname: "Jared's Stone",
        wsm: 10,
        wclass: "w1HS",
        zononly: false,
        isorb: true,
        isonehandsword: false,
        isjavelinorpolearm: false,
    },
    Javelin: {
        printname: "Javelin",
        wsm: -10,
        wclass: "w1HT",
        zononly: false,
        isorb: false,
        isonehandsword: false,
        isjavelinorpolearm: false,
    },
    JoStaff: {
        printname: "Jo Staff",
        wsm: -10,
        wclass: "wSTF",
        zononly: false,
        isorb: false,
        isonehandsword: false,
        isjavelinorpolearm: false,
    },
    Katar: {
        printname: "Katar",
        wsm: -10,
        wclass: "wHT1",
        zononly: false,
        isorb: false,
        isonehandsword: false,
        isjavelinorpolearm: false,
    },
    Knout: {
        printname: "Knout",
        wsm: -10,
        wclass: "w1HS",
        zononly: false,
        isorb: false,
        isonehandsword: false,
        isjavelinorpolearm: false,
    },
    Kris: {
        printname: "Kris",
        wsm: -20,
        wclass: "w1HT",
        zononly: false,
        isorb: false,
        isonehandsword: false,
        isjavelinorpolearm: false,
    },
    Lance: {
        printname: "Lance",
        wsm: 20,
        wclass: "w2HT",
        zononly: false,
        isorb: false,
        isonehandsword: false,
        isjavelinorpolearm: false,
    },
    LargeAxe: {
        printname: "Large Axe",
        wsm: -10,
        wclass: "wSTF",
        zononly: false,
        isorb: false,
        isonehandsword: false,
        isjavelinorpolearm: false,
    },
    LargeSiegeBow: {
        printname: "Large Siege Bow",
        wsm: 10,
        wclass: "wBOW",
        zononly: false,
        isorb: false,
        isonehandsword: false,
        isjavelinorpolearm: false,
    },
    LegendSpike: {
        printname: "Legend Spike",
        wsm: -10,
        wclass: "w1HT",
        zononly: false,
        isorb: false,
        isonehandsword: false,
        isjavelinorpolearm: false,
    },
    LegendSword: {
        printname: "Legend Sword",
        wsm: -15,
        wclass: "w2HS",
        zononly: false,
        isorb: false,
        isonehandsword: false,
        isjavelinorpolearm: false,
    },
    LegendaryMallet: {
        printname: "Legendary Mallet",
        wsm: 20,
        wclass: "w1HS",
        zononly: false,
        isorb: false,
        isonehandsword: false,
        isjavelinorpolearm: false,
    },
    LichWand: {
        printname: "Lich Wand",
        wsm: -20,
        wclass: "w1HS",
        zononly: false,
        isorb: false,
        isonehandsword: false,
        isjavelinorpolearm: false,
    },
    LightCrossbow: {
        printname: "Light Crossbow",
        wsm: -10,
        wclass: "wXBW",
        zononly: false,
        isorb: false,
        isonehandsword: false,
        isjavelinorpolearm: false,
    },
    LochaberAxe: {
        printname: "Lochaber Axe",
        wsm: 10,
        wclass: "wSTF",
        zononly: false,
        isorb: false,
        isonehandsword: false,
        isjavelinorpolearm: false,
    },
    LongBattleBow: {
        printname: "Long Battle Bow",
        wsm: 10,
        wclass: "wBOW",
        zononly: false,
        isorb: false,
        isonehandsword: false,
        isjavelinorpolearm: false,
    },
    LongBow: {
        printname: "Long Bow",
        wsm: 0,
        wclass: "wBOW",
        zononly: false,
        isorb: false,
        isonehandsword: false,
        isjavelinorpolearm: false,
    },
    LongStaff: {
        printname: "Long Staff",
        wsm: 0,
        wclass: "wSTF",
        zononly: false,
        isorb: false,
        isonehandsword: false,
        isjavelinorpolearm: false,
    },
    LongSword: {
        printname: "Long Sword",
        wsm: -10,
        wclass: "w1HS",
        zononly: false,
        isorb: false,
        isonehandsword: false,
        isjavelinorpolearm: false,
    },
    LongWarBow: {
        printname: "Long War Bow",
        wsm: 10,
        wclass: "wBOW",
        zononly: false,
        isorb: false,
        isonehandsword: false,
        isjavelinorpolearm: false,
    },
    Mace: {
        printname: "Mace",
        wsm: 0,
        wclass: "w1HS",
        zononly: false,
        isorb: false,
        isonehandsword: false,
        isjavelinorpolearm: false,
    },
    MaidenJavelin: {
        printname: "Maiden Javelin",
        wsm: -10,
        wclass: "w1HT",
        zononly: true,
        isorb: false,
        isonehandsword: false,
        isjavelinorpolearm: false,
    },
    MaidenPike: {
        printname: "Maiden Pike",
        wsm: 10,
        wclass: "w2HT",
        zononly: true,
        isorb: false,
        isonehandsword: false,
        isjavelinorpolearm: false,
    },
    MaidenSpear: {
        printname: "Maiden Spear",
        wsm: 0,
        wclass: "w2HT",
        zononly: true,
        isorb: false,
        isonehandsword: false,
        isjavelinorpolearm: false,
    },
    Mancatcher: {
        printname: "Mancatcher",
        wsm: -20,
        wclass: "w2HT",
        zononly: false,
        isorb: false,
        isonehandsword: false,
        isjavelinorpolearm: false,
    },
    MarteldeFer: {
        printname: "Martel de Fer",
        wsm: 20,
        wclass: "wSTF",
        zononly: false,
        isorb: false,
        isonehandsword: false,
        isjavelinorpolearm: false,
    },
    MatriarchalBow: {
        printname: "Matriarchal Bow",
        wsm: -10,
        wclass: "wBOW",
        zononly: true,
        isorb: false,
        isonehandsword: false,
        isjavelinorpolearm: false,
    },
    MatriarchalJavelin: {
        printname: "Matriarchal Javelin",
        wsm: -10,
        wclass: "w1HT",
        zononly: true,
        isorb: false,
        isonehandsword: false,
        isjavelinorpolearm: false,
    },
    MatriarchalPike: {
        printname: "Matriarchal Pike",
        wsm: 20,
        wclass: "w2HT",
        zononly: true,
        isorb: false,
        isonehandsword: false,
        isjavelinorpolearm: false,
    },
    MatriarchalSpear: {
        printname: "Matriarchal Spear",
        wsm: 0,
        wclass: "w2HT",
        zononly: true,
        isorb: false,
        isonehandsword: false,
        isjavelinorpolearm: false,
    },
    Maul: {
        printname: "Maul",
        wsm: 10,
        wclass: "wSTF",
        zononly: false,
        isorb: false,
        isonehandsword: false,
        isjavelinorpolearm: false,
    },
    MightyScepter: {
        printname: "Mighty Scepter",
        wsm: 0,
        wclass: "w1HS",
        zononly: false,
        isorb: false,
        isonehandsword: false,
        isjavelinorpolearm: false,
    },
    MilitaryAxe: {
        printname: "Military Axe",
        wsm: -10,
        wclass: "wSTF",
        zononly: false,
        isorb: false,
        isonehandsword: false,
        isjavelinorpolearm: false,
    },
    MilitaryPick: {
        printname: "Military Pick",
        wsm: -10,
        wclass: "w1HS",
        zononly: false,
        isorb: false,
        isonehandsword: false,
        isjavelinorpolearm: false,
    },
    MithrilPoint: {
        printname: "Mithril Point",
        wsm: 0,
        wclass: "w1HT",
        zononly: false,
        isorb: false,
        isonehandsword: false,
        isjavelinorpolearm: false,
    },
    MorningStar: {
        printname: "Morning Star",
        wsm: 10,
        wclass: "w1HS",
        zononly: false,
        isorb: false,
        isonehandsword: false,
        isjavelinorpolearm: false,
    },
    MythicalSword: {
        printname: "Mythical Sword",
        wsm: 0,
        wclass: "w1HS",
        zononly: false,
        isorb: false,
        isonehandsword: false,
        isjavelinorpolearm: false,
    },
    Naga: {
        printname: "Naga",
        wsm: 0,
        wclass: "w1HS",
        zononly: false,
        isorb: false,
        isonehandsword: false,
        isjavelinorpolearm: false,
    },
    OgreAxe: {
        printname: "Ogre Axe",
        wsm: 0,
        wclass: "wSTF",
        zononly: false,
        isorb: false,
        isonehandsword: false,
        isjavelinorpolearm: false,
    },
    OgreMaul: {
        printname: "Ogre Maul",
        wsm: 10,
        wclass: "wSTF",
        zononly: false,
        isorb: false,
        isonehandsword: false,
        isjavelinorpolearm: false,
    },
    Partizan: {
        printname: "Partizan",
        wsm: 10,
        wclass: "wSTF",
        zononly: false,
        isorb: false,
        isonehandsword: false,
        isjavelinorpolearm: false,
    },
    PelletBow: {
        printname: "Pellet Bow",
        wsm: -10,
        wclass: "wXBW",
        zononly: false,
        isorb: false,
        isonehandsword: false,
        isjavelinorpolearm: false,
    },
    PetrifiedWand: {
        printname: "Petrified Wand",
        wsm: 10,
        wclass: "w1HS",
        zononly: false,
        isorb: false,
        isonehandsword: false,
        isjavelinorpolearm: false,
    },
    Phaseblade: {
        printname: "Phaseblade",
        wsm: -30,
        wclass: "w1HS",
        zononly: false,
        isorb: false,
        isonehandsword: false,
        isjavelinorpolearm: false,
    },
    Pike: {
        printname: "Pike",
        wsm: 20,
        wclass: "w2HT",
        zononly: false,
        isorb: false,
        isonehandsword: false,
        isjavelinorpolearm: false,
    },
    Pilum: {
        printname: "Pilum",
        wsm: 0,
        wclass: "w1HT",
        zononly: false,
        isorb: false,
        isonehandsword: false,
        isjavelinorpolearm: false,
    },
    Poignard: {
        printname: "Poignard",
        wsm: -20,
        wclass: "w1HT",
        zononly: false,
        isorb: false,
        isonehandsword: false,
        isjavelinorpolearm: false,
    },
    Poleaxe: {
        printname: "Poleaxe",
        wsm: 10,
        wclass: "wSTF",
        zononly: false,
        isorb: false,
        isonehandsword: false,
        isjavelinorpolearm: false,
    },
    PolishedWand: {
        printname: "Polished Wand",
        wsm: 0,
        wclass: "w1HS",
        zononly: false,
        isorb: false,
        isonehandsword: false,
        isjavelinorpolearm: false,
    },
    Quarterstaff: {
        printname: "Quarterstaff",
        wsm: 0,
        wclass: "wSTF",
        zononly: false,
        isorb: false,
        isonehandsword: false,
        isjavelinorpolearm: false,
    },
    Quhab: {
        printname: "Quhab",
        wsm: 0,
        wclass: "wHT1",
        zononly: false,
        isorb: false,
        isonehandsword: false,
        isjavelinorpolearm: false,
    },
    RazorBow: {
        printname: "Razor Bow",
        wsm: -10,
        wclass: "wBOW",
        zononly: false,
        isorb: false,
        isonehandsword: false,
        isjavelinorpolearm: false,
    },
    ReflexBow: {
        printname: "Reflex Bow",
        wsm: 10,
        wclass: "wBOW",
        zononly: true,
        isorb: false,
        isonehandsword: false,
        isjavelinorpolearm: false,
    },
    ReinforcedMace: {
        printname: "Reinforced Mace",
        wsm: 0,
        wclass: "w1HS",
        zononly: false,
        isorb: false,
        isonehandsword: false,
        isjavelinorpolearm: false,
    },
    RepeatingCrossbow: {
        printname: "Repeating Crossbow",
        wsm: -40,
        wclass: "wXBW",
        zononly: false,
        isorb: false,
        isonehandsword: false,
        isjavelinorpolearm: false,
    },
    Rondel: {
        printname: "Rondel",
        wsm: 0,
        wclass: "w1HT",
        zononly: false,
        isorb: false,
        isonehandsword: false,
        isjavelinorpolearm: false,
    },
    RuneBow: {
        printname: "Rune Bow",
        wsm: 0,
        wclass: "wBOW",
        zononly: false,
        isorb: false,
        isonehandsword: false,
        isjavelinorpolearm: false,
    },
    RuneScepter: {
        printname: "Rune Scepter",
        wsm: 0,
        wclass: "w1HS",
        zononly: false,
        isorb: false,
        isonehandsword: false,
        isjavelinorpolearm: false,
    },
    RuneStaff: {
        printname: "Rune Staff",
        wsm: 20,
        wclass: "wSTF",
        zononly: false,
        isorb: false,
        isonehandsword: false,
        isjavelinorpolearm: false,
    },
    RuneSword: {
        printname: "Rune Sword",
        wsm: -10,
        wclass: "w1HS",
        zononly: false,
        isorb: false,
        isonehandsword: false,
        isjavelinorpolearm: false,
    },
    RunicTalons: {
        printname: "Runic Talons",
        wsm: -30,
        wclass: "wHT1",
        zononly: false,
        isorb: false,
        isonehandsword: false,
        isjavelinorpolearm: false,
    },
    Sabre: {
        printname: "Sabre",
        wsm: -10,
        wclass: "w1HS",
        zononly: false,
        isorb: false,
        isonehandsword: false,
        isjavelinorpolearm: false,
    },
    SacredGlobe: {
        printname: "Sacred Globe",
        wsm: -10,
        wclass: "w1HS",
        zononly: false,
        isorb: true,
        isonehandsword: false,
        isjavelinorpolearm: false,
    },
    Scepter: {
        printname: "Scepter",
        wsm: 0,
        wclass: "w1HS",
        zononly: false,
        isorb: false,
        isonehandsword: false,
        isjavelinorpolearm: false,
    },
    Scimitar: {
        printname: "Scimitar",
        wsm: -20,
        wclass: "w1HS",
        zononly: false,
        isorb: false,
        isonehandsword: false,
        isjavelinorpolearm: false,
    },
    ScissorsKatar: {
        printname: "Scissors Katar",
        wsm: -10,
        wclass: "wHT1",
        zononly: false,
        isorb: false,
        isonehandsword: false,
        isjavelinorpolearm: false,
    },
    ScissorsQuhab: {
        printname: "Scissors Quhab",
        wsm: 0,
        wclass: "wHT1",
        zononly: false,
        isorb: false,
        isonehandsword: false,
        isjavelinorpolearm: false,
    },
    ScissorsSuwayyah: {
        printname: "Scissors Suwayyah",
        wsm: 0,
        wclass: "wHT1",
        zononly: false,
        isorb: false,
        isonehandsword: false,
        isjavelinorpolearm: false,
    },
    Scourge: {
        printname: "Scourge",
        wsm: -10,
        wclass: "w1HS",
        zononly: false,
        isorb: false,
        isonehandsword: false,
        isjavelinorpolearm: false,
    },
    Scythe: {
        printname: "Scythe",
        wsm: -10,
        wclass: "wSTF",
        zononly: false,
        isorb: false,
        isonehandsword: false,
        isjavelinorpolearm: false,
    },
    SeraphRod: {
        printname: "Seraph Rod",
        wsm: 10,
        wclass: "w1HS",
        zononly: false,
        isorb: false,
        isonehandsword: false,
        isjavelinorpolearm: false,
    },
    ShadowBow: {
        printname: "Shadow Bow",
        wsm: 0,
        wclass: "wBOW",
        zononly: false,
        isorb: false,
        isonehandsword: false,
        isjavelinorpolearm: false,
    },
    Shamshir: {
        printname: "Shamshir",
        wsm: -10,
        wclass: "w1HS",
        zononly: false,
        isorb: false,
        isonehandsword: false,
        isjavelinorpolearm: false,
    },
    Shillelagh: {
        printname: "Shillelagh",
        wsm: 0,
        wclass: "wSTF",
        zononly: false,
        isorb: false,
        isonehandsword: false,
        isjavelinorpolearm: false,
    },
    ShortBattleBow: {
        printname: "Short Battle Bow",
        wsm: 0,
        wclass: "wBOW",
        zononly: false,
        isorb: false,
        isonehandsword: false,
        isjavelinorpolearm: false,
    },
    ShortBow: {
        printname: "Short Bow",
        wsm: 5,
        wclass: "wBOW",
        zononly: false,
        isorb: false,
        isonehandsword: false,
        isjavelinorpolearm: false,
    },
    ShortSiegeBow: {
        printname: "Short Siege Bow",
        wsm: 0,
        wclass: "wBOW",
        zononly: false,
        isorb: false,
        isonehandsword: false,
        isjavelinorpolearm: false,
    },
    ShortSpear: {
        printname: "Short Spear",
        wsm: 10,
        wclass: "w1HT",
        zononly: false,
        isorb: false,
        isonehandsword: false,
        isjavelinorpolearm: false,
    },
    ShortStaff: {
        printname: "Short Staff",
        wsm: -10,
        wclass: "wSTF",
        zononly: false,
        isorb: false,
        isonehandsword: false,
        isjavelinorpolearm: false,
    },
    ShortSword: {
        printname: "Short Sword",
        wsm: 0,
        wclass: "w1HS",
        zononly: false,
        isorb: false,
        isonehandsword: false,
        isjavelinorpolearm: false,
    },
    ShortWarBow: {
        printname: "Short War Bow",
        wsm: 0,
        wclass: "wBOW",
        zononly: false,
        isorb: false,
        isonehandsword: false,
        isjavelinorpolearm: false,
    },
    SiegeCrossbow: {
        printname: "Siege Crossbow",
        wsm: 0,
        wclass: "wXBW",
        zononly: false,
        isorb: false,
        isonehandsword: false,
        isjavelinorpolearm: false,
    },
    SilverEdgedAxe: {
        printname: "Silver-edged Axe",
        wsm: 0,
        wclass: "wSTF",
        zononly: false,
        isorb: false,
        isonehandsword: false,
        isjavelinorpolearm: false,
    },
    Simbilan: {
        printname: "Simbilan",
        wsm: 10,
        wclass: "w1HT",
        zononly: false,
        isorb: false,
        isonehandsword: false,
        isjavelinorpolearm: false,
    },
    SmallCrescent: {
        printname: "Small Crescent",
        wsm: 10,
        wclass: "w1HS",
        zononly: false,
        isorb: false,
        isonehandsword: false,
        isjavelinorpolearm: false,
    },
    SmokedSphere: {
        printname: "Smoked Sphere",
        wsm: 0,
        wclass: "w1HS",
        zononly: false,
        isorb: true,
        isonehandsword: false,
        isjavelinorpolearm: false,
    },
    SparklingBall: {
        printname: "Sparkling Ball",
        wsm: 0,
        wclass: "w1HS",
        zononly: false,
        isorb: true,
        isonehandsword: false,
        isjavelinorpolearm: false,
    },
    Spear: {
        printname: "Spear",
        wsm: -10,
        wclass: "w2HT",
        zononly: false,
        isorb: false,
        isonehandsword: false,
        isjavelinorpolearm: false,
    },
    Spetum: {
        printname: "Spetum",
        wsm: 0,
        wclass: "w2HT",
        zononly: false,
        isorb: false,
        isonehandsword: false,
        isjavelinorpolearm: false,
    },
    Spiculum: {
        printname: "Spiculum",
        wsm: 20,
        wclass: "w1HT",
        zononly: false,
        isorb: false,
        isonehandsword: false,
        isjavelinorpolearm: false,
    },
    SpiderBow: {
        printname: "Spider Bow",
        wsm: 5,
        wclass: "wBOW",
        zononly: false,
        isorb: false,
        isonehandsword: false,
        isjavelinorpolearm: false,
    },
    SpikedClub: {
        printname: "Spiked Club",
        wsm: 0,
        wclass: "w1HS",
        zononly: false,
        isorb: false,
        isonehandsword: false,
        isjavelinorpolearm: false,
    },
    StagBow: {
        printname: "Stag Bow",
        wsm: 0,
        wclass: "wBOW",
        zononly: true,
        isorb: false,
        isonehandsword: false,
        isjavelinorpolearm: false,
    },
    Stalagmite: {
        printname: "Stalagmite",
        wsm: 10,
        wclass: "wSTF",
        zononly: false,
        isorb: false,
        isonehandsword: false,
        isjavelinorpolearm: false,
    },
    Stiletto: {
        printname: "Stiletto",
        wsm: -10,
        wclass: "w1HT",
        zononly: false,
        isorb: false,
        isonehandsword: false,
        isjavelinorpolearm: false,
    },
    StygianPike: {
        printname: "Stygian Pike",
        wsm: 0,
        wclass: "w2HT",
        zononly: false,
        isorb: false,
        isonehandsword: false,
        isjavelinorpolearm: false,
    },
    StygianPilum: {
        printname: "Stygian Pilum",
        wsm: 0,
        wclass: "w1HT",
        zononly: false,
        isorb: false,
        isonehandsword: false,
        isjavelinorpolearm: false,
    },
    Suwayyah: {
        printname: "Suwayyah",
        wsm: 0,
        wclass: "wHT1",
        zononly: false,
        isorb: false,
        isonehandsword: false,
        isjavelinorpolearm: false,
    },
    SwirlingCrystal: {
        printname: "Swirling Crystal",
        wsm: 10,
        wclass: "w1HS",
        zononly: false,
        isorb: true,
        isonehandsword: false,
        isjavelinorpolearm: false,
    },
    Tabar: {
        printname: "Tabar",
        wsm: 10,
        wclass: "wSTF",
        zononly: false,
        isorb: false,
        isonehandsword: false,
        isjavelinorpolearm: false,
    },
    Thresher: {
        printname: "Thresher",
        wsm: -10,
        wclass: "wSTF",
        zononly: false,
        isorb: false,
        isonehandsword: false,
        isjavelinorpolearm: false,
    },
    ThrowingAxe: {
        printname: "Throwing Axe",
        wsm: 10,
        wclass: "w1HS",
        zononly: false,
        isorb: false,
        isonehandsword: false,
        isjavelinorpolearm: false,
    },
    ThrowingKnife: {
        printname: "Throwing Knife",
        wsm: 0,
        wclass: "w1HT",
        zononly: false,
        isorb: false,
        isonehandsword: false,
        isjavelinorpolearm: false,
    },
    ThrowingSpear: {
        printname: "Throwing Spear",
        wsm: -10,
        wclass: "w1HT",
        zononly: false,
        isorb: false,
        isonehandsword: false,
        isjavelinorpolearm: false,
    },
    ThunderMaul: {
        printname: "Thunder Maul",
        wsm: 20,
        wclass: "wSTF",
        zononly: false,
        isorb: false,
        isonehandsword: false,
        isjavelinorpolearm: false,
    },
    Tomahawk: {
        printname: "Tomahawk",
        wsm: 0,
        wclass: "w1HS",
        zononly: false,
        isorb: false,
        isonehandsword: false,
        isjavelinorpolearm: false,
    },
    TombWand: {
        printname: "Tomb Wand",
        wsm: -20,
        wclass: "w1HS",
        zononly: false,
        isorb: false,
        isonehandsword: false,
        isjavelinorpolearm: false,
    },
    Trident: {
        printname: "Trident",
        wsm: 0,
        wclass: "w2HT",
        zononly: false,
        isorb: false,
        isonehandsword: false,
        isjavelinorpolearm: false,
    },
    Truncheon: {
        printname: "Truncheon",
        wsm: -10,
        wclass: "w1HS",
        zononly: false,
        isorb: false,
        isonehandsword: false,
        isjavelinorpolearm: false,
    },
    Tulwar: {
        printname: "Tulwar",
        wsm: 20,
        wclass: "w1HS",
        zononly: false,
        isorb: false,
        isonehandsword: false,
        isjavelinorpolearm: false,
    },
    TuskSword: {
        printname: "Tusk Sword",
        wsm: 0,
        wclass: "w2HS",
        zononly: false,
        isorb: false,
        isonehandsword: false,
        isjavelinorpolearm: false,
    },
    TwinAxe: {
        printname: "Twin Axe",
        wsm: 10,
        wclass: "w1HS",
        zononly: false,
        isorb: false,
        isonehandsword: false,
        isjavelinorpolearm: false,
    },
    TwoHandedSword: {
        printname: "Two-Handed Sword",
        wsm: 0,
        wclass: "w2HS",
        zononly: false,
        isorb: false,
        isonehandsword: false,
        isjavelinorpolearm: false,
    },
    TyrantClub: {
        printname: "Tyrant Club",
        wsm: 0,
        wclass: "w1HS",
        zononly: false,
        isorb: false,
        isonehandsword: false,
        isjavelinorpolearm: false,
    },
    UnearthedWand: {
        printname: "Unearthed Wand",
        wsm: 0,
        wclass: "w1HS",
        zononly: false,
        isorb: false,
        isonehandsword: false,
        isjavelinorpolearm: false,
    },
    VortexOrb: {
        printname: "Vortex Orb",
        wsm: 0,
        wclass: "w1HS",
        zononly: false,
        isorb: true,
        isonehandsword: false,
        isjavelinorpolearm: false,
    },
    Voulge: {
        printname: "Voulge",
        wsm: 0,
        wclass: "wSTF",
        zononly: false,
        isorb: false,
        isonehandsword: false,
        isjavelinorpolearm: false,
    },
    WalkingStick: {
        printname: "Walking Stick",
        wsm: -10,
        wclass: "wSTF",
        zononly: false,
        isorb: false,
        isonehandsword: false,
        isjavelinorpolearm: false,
    },
    Wand: {
        printname: "Wand",
        wsm: 0,
        wclass: "w1HS",
        zononly: false,
        isorb: false,
        isonehandsword: false,
        isjavelinorpolearm: false,
    },
    WarAxe: {
        printname: "War Axe",
        wsm: 0,
        wclass: "w1HS",
        zononly: false,
        isorb: false,
        isonehandsword: false,
        isjavelinorpolearm: false,
    },
    WarClub: {
        printname: "War Club",
        wsm: 10,
        wclass: "wSTF",
        zononly: false,
        isorb: false,
        isonehandsword: false,
        isjavelinorpolearm: false,
    },
    WarDart: {
        printname: "War Dart",
        wsm: -20,
        wclass: "w1HT",
        zononly: false,
        isorb: false,
        isonehandsword: false,
        isjavelinorpolearm: false,
    },
    WarFist: {
        printname: "War Fist",
        wsm: 10,
        wclass: "wHT1",
        zononly: false,
        isorb: false,
        isonehandsword: false,
        isjavelinorpolearm: false,
    },
    WarFork: {
        printname: "War Fork",
        wsm: -20,
        wclass: "w2HT",
        zononly: false,
        isorb: false,
        isonehandsword: false,
        isjavelinorpolearm: false,
    },
    WarHammer: {
        printname: "War Hammer",
        wsm: 20,
        wclass: "w1HS",
        zononly: false,
        isorb: false,
        isonehandsword: false,
        isjavelinorpolearm: false,
    },
    WarJavelin: {
        printname: "War Javelin",
        wsm: -10,
        wclass: "w1HT",
        zononly: false,
        isorb: false,
        isonehandsword: false,
        isjavelinorpolearm: false,
    },
    WarPike: {
        printname: "War Pike",
        wsm: 20,
        wclass: "w2HT",
        zononly: false,
        isorb: false,
        isonehandsword: false,
        isjavelinorpolearm: false,
    },
    WarScepter: {
        printname: "War Scepter",
        wsm: -10,
        wclass: "w1HS",
        zononly: false,
        isorb: false,
        isonehandsword: false,
        isjavelinorpolearm: false,
    },
    WarScythe: {
        printname: "War Scythe",
        wsm: -10,
        wclass: "wSTF",
        zononly: false,
        isorb: false,
        isonehandsword: false,
        isjavelinorpolearm: false,
    },
    WarSpear: {
        printname: "War Spear",
        wsm: -10,
        wclass: "w2HT",
        zononly: false,
        isorb: false,
        isonehandsword: false,
        isjavelinorpolearm: false,
    },
    WarSpike: {
        printname: "War Spike",
        wsm: -10,
        wclass: "w1HS",
        zononly: false,
        isorb: false,
        isonehandsword: false,
        isjavelinorpolearm: false,
    },
    WarStaff: {
        printname: "War Staff",
        wsm: 20,
        wclass: "wSTF",
        zononly: false,
        isorb: false,
        isonehandsword: false,
        isjavelinorpolearm: false,
    },
    WarSword: {
        printname: "War Sword",
        wsm: 0,
        wclass: "w1HS",
        zononly: false,
        isorb: false,
        isonehandsword: false,
        isjavelinorpolearm: false,
    },
    WardBow: {
        printname: "Ward Bow",
        wsm: 0,
        wclass: "wBOW",
        zononly: false,
        isorb: false,
        isonehandsword: false,
        isjavelinorpolearm: false,
    },
    WingedAxe: {
        printname: "Winged Axe",
        wsm: -10,
        wclass: "w1HS",
        zononly: false,
        isorb: false,
        isonehandsword: false,
        isjavelinorpolearm: false,
    },
    WingedHarpoon: {
        printname: "Winged Harpoon",
        wsm: -10,
        wclass: "w1HT",
        zononly: false,
        isorb: false,
        isonehandsword: false,
        isjavelinorpolearm: false,
    },
    WingedKnife: {
        printname: "Winged Knife",
        wsm: -20,
        wclass: "w1HT",
        zononly: false,
        isorb: false,
        isonehandsword: false,
        isjavelinorpolearm: false,
    },
    WristBlade: {
        printname: "Wrist Blade",
        wsm: 0,
        wclass: "wHT1",
        zononly: false,
        isorb: false,
        isonehandsword: false,
        isjavelinorpolearm: false,
    },
    WristSpike: {
        printname: "Wrist Spike",
        wsm: -10,
        wclass: "wHT1",
        zononly: false,
        isorb: false,
        isonehandsword: false,
        isjavelinorpolearm: false,
    },
    WristSword: {
        printname: "Wrist Sword",
        wsm: -10,
        wclass: "wHT1",
        zononly: false,
        isorb: false,
        isonehandsword: false,
        isjavelinorpolearm: false,
    },
    Yari: {
        printname: "Yari",
        wsm: 0,
        wclass: "w2HT",
        zononly: false,
        isorb: false,
        isonehandsword: false,
        isjavelinorpolearm: false,
    },
    YewWand: {
        printname: "Yew Wand",
        wsm: 10,
        wclass: "w1HS",
        zononly: false,
        isorb: false,
        isonehandsword: false,
        isjavelinorpolearm: false,
    },
    Zweihander: {
        printname: "Zweihander",
        wsm: -10,
        wclass: "w2HS",
        zononly: false,
        isorb: false,
        isonehandsword: false,
        isjavelinorpolearm: false,
    }
};
